export const REQUEST_CHANGE = 'REQUEST_CHANGE'
export const REQUEST_NOT_JSON = 'REQUEST_NOT_JSON'
export const REQUEST_ARE_JSON = 'REQUEST_ARE_JSON'
export const REQUEST_SUBMITTED = 'REQUEST_SUBMITTED'

export const HISTORY_PUSH_ITEM = 'HISTORY_PUSH_ITEM'
export const HISTORY_CLEAR = 'HISTORY_CLEAR'
export const HISTORY_DELETE_ITEM = 'HISTORY_DELETE_ITEM'
export const HISTORY_TO_LOCAL_STORAGE = 'HISTORY_TO_LOCAL_STORAGE'

export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_LOGIN = 'AUTH_LOGIN'